In [3]:
import numpy as np

## Simple Matrix using Numpy 

In [4]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


### Home Work
- Create a 3×3 matrix in Python using NumPy.

In [5]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Home work
- Create a scalar and a vector in Python.

In [7]:
scalar = 11
print("Scalar : ",scalar)

vector = np.array([1,2,3])
print("Vector : ",vector)

Scalar :  11
Vector :  [1 2 3]


## Vector Operations

### Vector Addition & Subtraction 

In [10]:
A = np.array([1,2,3])
B = np.array([3,2,1])
print("Vector Addition: ",(A+B))
print("Vector Subtraction: ",(A-B))


Vector Addition:  [4 4 4]
Vector Subtraction:  [-2  0  2]


### Scalar Multiplication

In [12]:
C = np.array([2, 3, 4])
scalar = 3

result = scalar * C

print("Scalar Multiplication:", result)


Scalar Multiplication: [ 6  9 12]


###  Dot Product

In [13]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

dot_product = np.dot(A, B)

print("Dot Product:", dot_product)


Dot Product: 32


### Cross Product (Vector Product)

In [15]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

cross_product = np.cross(A, B)
print("Cross Product:", cross_product)

Cross Product: [-3  6 -3]


# Matrix
- matrix is represented as a list of lists in NumPy. Each inner list represents a row of the matrix.


In [16]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix A:\n", A)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Basic Matrix Operations

### Addition & Subtraction

In [17]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

add_result = A + B
sub_result = A - B

print("Matrix Addition:\n", add_result)
print("Matrix Subtraction:\n", sub_result)


Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]


### Scalar Multiplication

In [19]:
scalar = 2
scalar_mult = scalar * A
print("Scalar Multiplication:\n", scalar_mult)


Scalar Multiplication:
 [[2 4]
 [6 8]]


### Matrix Multiplication (Dot Product)

In [20]:
matrix_mult = np.dot(A, B)
print("Matrix Multiplication:\n", matrix_mult)


Matrix Multiplication:
 [[19 22]
 [43 50]]


### Determinant of a Matrix

In [22]:
A = np.array([[4, 3], [6, 3]])
det_A = np.linalg.det(A)

print("Determinant of A:", det_A)

Determinant of A: -6.0


### Inverse of a Matrix


In [23]:
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)


Inverse of A:
 [[-0.5         0.5       ]
 [ 1.         -0.66666667]]


### Singular & Non-Singular Matrices
- A matrix is classified as singular or non-singular based on its determinant.
- ✅ Non-Singular Matrix → Has a non-zero determinant (invertible)
- ❌ Singular Matrix → Has a zero determinant (not invertible)

In [25]:
A = np.array([[1, 2], [3, 4]])
det_A = np.linalg.det(A)

if det_A != 0 :
    print("Matrix A is Non-Singular (Invertible)")
else:
    print("Matrix A is Singular (Not Invertible)")

Matrix A is Non-Singular (Invertible)


In [26]:
B = np.array([[2,1],[4,2]])
det_B = np.linalg.det(B)

if det_B != 0 :
    print("Matrix A is Non-Singular (Invertible)")
else:
    print("Matrix A is Singular (Not Invertible)")


Matrix A is Singular (Not Invertible)


### Rank of a Matrix
- The rank of a matrix is the number of linearly independent rows or columns.
- ✅ Linearly Independent → No vector in the set can be written as a combination of the others.
- ❌ Linearly Dependent → At least one vector is a combination of others.
- Vectors V1 = [1, 2], V2 = [2, 4] --> V2 = 2 × V1


In [28]:
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rank_B = np.linalg.matrix_rank(B)

print("Rank of Matrix B:", rank_B)

Rank of Matrix B: 2
