In [5]:
import numpy as np

# NumPy Functions

## 1️⃣ Array Creation Functions
- `np.array(object)` - Creates an array.
- `np.zeros(shape)` - Creates an array filled with zeros.
- `np.ones(shape)` - Creates an array filled with ones.
- `np.empty(shape)` - Creates an empty array (values are not initialized).
- `np.eye(N)` - Creates an identity matrix.
- `np.arange(start, stop, step)` - Creates an array with values within a specified range.
- `np.linspace(start, stop, num)` - Creates an array with evenly spaced values.
- `np.full(shape, value)` - Creates an array filled with a specified value.
- `np.random.rand(d0, d1, ..., dn)` - Creates an array with random values (between 0 and 1).
- `np.random.randint(low, high, size)` - Creates an array with random integers.

# Examples
## **np.array(list or tuple )** 
- Creates a NumPy array from a Python list or another sequence.

In [6]:
# Example
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


## **np.zeros((row,col))**  
- Creates an array of a given shape filled with **zeros**.

In [11]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


## **np.ones((row,col))**  
- Creates an array of a given shape filled with **ones**.

In [14]:
arr = np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


## **np.empty((row,col))**  
- Creates an **empty array** with uninitialized values.
- (Note: The values are not necessarily zero, they are just placeholders and uninitialized.)

In [17]:
arr = np.empty((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


## **np.eye(N, M=None, k=0, dtype=float, order='C')**  
- Creates an **identity matrix** with 1s on the diagonal and 0s elsewhere.
- N: Number of rows in the output.
- M: Number of columns (if None, defaults to N, creating a square matrix).
- k: Diagonal offset (0 for the main diagonal, positive for diagonals above, negative for below).


In [29]:
mat = np.eye(3,dtype=float)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## **np.arange(start,stop,step)**  
- Creates an array with values in a specified range (**range_array**).


In [31]:
range_array= np.arange(0,10,2)
print(range_array)

[0 2 4 6 8]



## **np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)**  
- Creates an array with evenly spaced values between a start and stop value (**Linear Space**).
    - **start**: Starting value of the sequence.
    - **stop**: End value of the sequence.
    - **num**: Number of values to generate.
    - **endpoint**: If True, the stop value is included.
    - **retstep**: If True, it also returns the step size.
    - **dtype**: Data type for the output array.
    - **axis**: Axis along which the values are generated.


In [35]:
linear_space = np.linspace(1,2,6)
print(linear_space)

[1.  1.2 1.4 1.6 1.8 2. ]


## **np.full(shape, fill_value, dtype=None, order='C')**  
- Creates an array filled with a specified value.


In [37]:
arr = np.full((2,2),11)
print(arr)

[[11 11]
 [11 11]]


## **np.random.rand()**  
- Creates an array with random values between 0 and 1.`

In [39]:
# 2X 3 matrix
random_array = np.random.rand(2, 3)
print(random_array)


[[0.40863948 0.49270409 0.63150383]
 [0.65602243 0.46433595 0.09107531]]


## **np.random.randint(low, high=None, size=None, dtype=int)**  
- Creates an array with random integers from a specified range.
    - **low**: Lowest integer to be drawn.
    - **high**: If provided, the range is [low, high). If not, the range is [0, low).
    - **size**: Output shape.
    - **dtype**: Data type of the output array (default is int).

In [40]:
random_int_array = np.random.randint(10, 50, size=(2, 3))
print(random_int_array)


[[23 38 28]
 [12 36 16]]


In [41]:
random_int_array = np.random.randint(10, size=(2, 3))
print(random_int_array)


[[1 1 2]
 [1 2 3]]


# Practice

1. **Create a 1D array from a list**  
   Convert the Python list `[1, 2, 3, 4, 5]` into a NumPy array.

In [42]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


2. **Create a 3x3 array of zeros**  
   Create a 3x3 array filled with zeros.

In [43]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. **Create a 2D array of ones with shape (2, 5)**  
   Use `np.ones()` to create a 2x5 array filled with ones.

In [44]:
arr = np.ones((2,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


4. **Generate an array with values from 10 to 20**  
   Use `np.arange()` to generate an array with values from 10 to 20 (inclusive).
   

In [47]:
arr = np.arange(10,21,1)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


5. **Create an identity matrix of size 4**  
   Create a 4x4 identity matrix.

In [50]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


6. **Create a 4x4 array with random integers**  
   Create a 4x4 array with random integers between 0 and 100 using `np.random.randint()`.

In [55]:
arr = np.random.randint(100,size=(4,4))
print(arr)

[[62 87 17 23]
 [94 73 95 16]
 [43 15 86 85]
 [64 22 28 53]]


3. **Create an array of even numbers between 0 and 20**  
   Use `np.arange()` to generate an array with even numbers between 0 and 20.

In [104]:
even = np.arange(0,20,2)
print(even)

[ 0  2  4  6  8 10 12 14 16 18]


## 2️⃣ Array Inspection Functions
- `np.shape(arr)` - Returns the shape of the array.
- `np.size(arr)` - Returns the total number of elements.
- `np.ndim(arr)` - Returns the number of dimensions (axes).
- `arr.dtype` - Returns the data type of the elements in the array.
- `np.itemsize(arr)` - Returns the size (in bytes) of each array element.
- `np.length(arr)` - Returns the length of the array.
- `np.info(np.func)` - Displays information about a NumPy function.

### Example 

In [84]:
arr = np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## **np.shape()**
- Returns shape(row,column) of the array

In [86]:
print(np.shape(arr))

(3, 3)


## **np.size()**
- Returns the total number of elements in an array

In [87]:
print(np.size(arr))

9


## **np.ndim(arr)**
- Returns the number of dimensions (axes).

In [96]:
print(np.ndim(arr))

2


## **arr.dtype**
- Returns the data type of the elements in the array.

In [98]:
arr = np.array([1, 2, 3])
print(arr.dtype)  

int64


## **np.itemsize()**
- Returns the size (in bytes) of each element in the array.

In [101]:
arr = np.array([1, 2, 3])
print(arr.itemsize)

8


## **np.info()**
- Displays information about a NumPy function or method.

In [100]:
print(np.info(arr)) 

class:  ndarray
shape:  (3,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x600002913fc0
byteorder:  little
byteswap:  False
type: int64
None


In [103]:
print(np.info(np.array))

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the same object


# 🟡 Medium Level:

1. **Reshape an array**  
   Create a 1D array from 1 to 9, then reshape it into a 3x3 matrix.


In [52]:
arr= np.array([1,2,3,4,5,6,7,8,9])
reshaped_arr = np.reshape(arr,(3,3))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


4. **Find the maximum and minimum values**  
   Create an array of random integers and find the maximum and minimum values in the array.

In [60]:
arr = np.random.randint(100,size=(3,3))
print(arr)
min_val = np.min(arr)
print(min_val)
max_val = np.max(arr)
print(max_val)

[[19 87 23]
 [ 5 60 78]
 [38 70 26]]
5
87


5. **Find the sum of all elements in a 2D array**  
   Create a 3x3 matrix with values from 1 to 9 and find the sum of all its elements.

In [79]:
#matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix = np.arange(1,10).reshape(3,3)
print(matrix)
Sum_of_Matrix = np.sum(matrix)
print(Sum_of_Matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45


## 3️⃣ Mathematical Functions
- `np.add(arr1, arr2)` - Element-wise addition.
- `np.subtract(arr1, arr2)` - Element-wise subtraction.
- `np.multiply(arr1, arr2)` - Element-wise multiplication.
- `np.divide(arr1, arr2)` - Element-wise division.
- `np.power(arr, n)` - Raises elements to the power of n.
- `np.sqrt(arr)` - Computes the square root of each element.
- `np.sin(arr)`, `np.cos(arr)`, `np.tan(arr)` - Trigonometric functions.
- `np.log(arr)` - Natural logarithm of elements.
- `np.exp(arr)` - Exponential of elements.
- `np.abs(arr)` - Absolute value of elements.
- `np.sum(arr)` - Sum of elements.
- `np.prod(arr)` - Product of elements.
- `np.cumsum(arr)` - Cumulative sum of elements.
- `np.cumprod(arr)` - Cumulative product of elements.

In [117]:
# Sample array
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

### 1️⃣ Addition

In [119]:
print(np.add(arr1, arr2))  # [6 6 6 6 6]

[6 6 6 6 6]


### 2️⃣ Subtraction

In [131]:
print(np.subtract(arr1, arr2))  # [-4 -2  0  2  4]

[-4 -2  0  2  4]


### 3️⃣ Multiplication

In [132]:
print(np.multiply(arr1, arr2))  # [5 8 9 8 5]

[5 8 9 8 5]


### 4️⃣ Division

In [133]:
print(np.divide(arr1, arr2))  # [0.2 0.5 1.  2.  5. ]

[0.2 0.5 1.  2.  5. ]


### 5️⃣ Power (Raise to Power n)

In [134]:
print(np.power(arr1, 2))  # [ 1  4  9 16 25]

[ 1  4  9 16 25]


### 6️⃣ Square Root

In [135]:
print(np.sqrt(arr1))  # [1.         1.41421356 1.73205081 2.         2.23606798]

[1.         1.41421356 1.73205081 2.         2.23606798]


### 7️⃣ Trigonometric Functions

In [136]:
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))  # [ 0.  1.  0.]
print(np.cos(angles))  # [ 1.  0. -1.]
print(np.tan(angles))  # [ 0.  1.634E16  0.]

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


### 8️⃣ Logarithm (Natural Log)

In [137]:
print(np.log(arr1))  # [0.         0.69314718 1.09861229 1.38629436 1.60943791]

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


### 9️⃣ Exponential

In [138]:
print(np.exp(arr1))  # [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


### 🔟 Absolute Value

In [139]:
arr_neg = np.array([-1, -2, -3, 4, 5])
print(np.abs(arr_neg))  # [1 2 3 4 5]

[1 2 3 4 5]


### 1️⃣1️⃣ Sum of Elements

In [140]:
print(np.sum(arr1))  # 15

15


### 1️⃣2️⃣ Product of Elements

In [141]:
print(np.prod(arr1))  # 120

120


### 1️⃣3️⃣ Cumulative Sum

In [142]:
print(np.cumsum(arr1))  # [ 1  3  6 10 15]

[ 1  3  6 10 15]


### 1️⃣4️⃣ Cumulative Product

In [144]:
print(np.cumprod(arr1))  # [  1   2   6  24 120]

[  1   2   6  24 120]


## 4️⃣ Array Reshaping & Manipulation Functions
- `np.reshape(arr, new_shape)` - Reshapes the array to a new shape.
- `np.ravel(arr)` - Flattens the array to 1D.
- `np.transpose(arr)` - Transposes the array (rows become columns).
- `np.swapaxes(arr, axis1, axis2)` - Swaps two axes of the array.
- `np.expand_dims(arr, axis)` - Expands an array by adding a new axis.
- `np.squeeze(arr)` - Removes single-dimensional entries from the shape.
- `np.concatenate((arr1, arr2), axis)` - Concatenates two arrays along a given axis.
- `np.stack(arrays, axis)` - Stacks arrays along a new axis.
- `np.hstack(arrays)` - Stacks arrays horizontally.
- `np.vstack(arrays)` - Stacks arrays vertically.
- `np.split(arr, indices_or_sections)` - Splits an array into sub-arrays.
- `np.tile(arr, reps)` - Repeats an array.

### Examples

### `np.reshape(arr, new_shape)`
- Reshapes the array to a new shape.

In [145]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = np.reshape(arr, (2, 3))
print(reshaped)


[[1 2 3]
 [4 5 6]]


## 4️⃣ Array Indexing & Slicing
- `arr[start:stop:step]` - Slices an array.
- `np.where(condition)` - Returns the indices where the condition is True.
- `np.take(arr, indices)` - Takes elements from an array along an axis.
- `np.choose(choices, index)` - Selects elements based on indices.
- `np.nonzero(arr)` - Returns the indices of non-zero elements.
- `np.ix_(*arrays)` - Constructs an open mesh grid for array indexing.


## 6️⃣ Sorting, Searching, & Counting
- `np.sort(arr)` - Returns a sorted copy of the array.
- `np.argsort(arr)` - Returns the indices that would sort the array.
- `np.argmin(arr)` - Returns the index of the minimum value.
- `np.argmax(arr)` - Returns the index of the maximum value.
- `np.searchsorted(arr, value)` - Finds indices where elements should be inserted.
- `np.count_nonzero(arr)` - Counts non-zero elements.

## 7️⃣ Broadcasting & Vectorization
- `np.vectorize(pyfunc)` - Vectorizes a Python function so that it applies to arrays.
- `np.broadcast(arr1, arr2)` - Broadcasts two arrays to a common shape.



## 8️⃣ Linear Algebra Functions
- `np.dot(arr1, arr2)` - Dot product of two arrays.
- `np.matmul(arr1, arr2)` - Matrix product of two arrays.
- `np.cross(arr1, arr2)` - Cross product of two arrays.
- `np.linalg.inv(arr)` - Computes the inverse of a matrix.
- `np.linalg.eig(arr)` - Computes the eigenvalues and eigenvectors of a matrix.
- `np.linalg.det(arr)` - Computes the determinant of a matrix.
- `np.linalg.solve(a, b)` - Solves a linear matrix equation.


## 9️⃣ Random Numbers Functions
- `np.random.rand(d0, d1, ..., dn)` - Random values in [0,1).
- `np.random.randn(d0, d1, ..., dn)` - Random values from a normal distribution.
- `np.random.randint(low, high, size)` - Random integers from low to high.
- `np.random.choice(arr, size)` - Randomly select elements from an array.
- `np.random.shuffle(arr)` - Shuffles the elements in an array.
- `np.random.seed(seed)` - Seeds the random number generator.


## 🔟 Statistical Functions
- `np.min(arr)` - Minimum value in the array.
- `np.max(arr)` - Maximum value in the array.
- `np.percentile(arr, q)` - Percentile of the array.
- `np.median(arr)` - Median value.
- `np.mean(arr)` - Mean (average) value.
- `np.std(arr)` - Standard deviation.
- `np.var(arr)` - Variance.
- `np.corrcoef(arr)` - Correlation coefficient matrix.
- `np.histogram(arr)` - Computes the histogram.