# Numpy
- NumPy is a Python library used for working with arrays.


In [3]:
import numpy as np

## Advantages of NumPy Over Python Lists
### 1. Speed (Faster Computation)
   - NumPy arrays use **contiguous memory allocation**, making operations 50x faster than Python lists.
   - Uses optimized vectorized operations instead of slow for loops.

#### Example

In [4]:

import time

lst = list(range(1000000))
arr = np.array(lst)

start = time.time()
sum(lst)  # Using Python list
end = time.time()
print("List Time:", end - start)

start = time.time()
np.sum(arr)  # Using NumPy
end = time.time()
print("NumPy Time:", end - start)


List Time: 0.003153085708618164
NumPy Time: 0.0004150867462158203


### 2.Less Memory Usage
- Python lists store each element separately (with metadata), making them memory-heavy.
- NumPy stores elements efficiently in a fixed-type array, using less memory.

In [5]:
import sys

lst = list(range(1000))
arr = np.array(lst)

print("List Memory:", sys.getsizeof(lst))
print("NumPy Memory:", arr.nbytes)


List Memory: 8056
NumPy Memory: 8000


### 3.Supports Multi-Dimensional Arrays
- Lists are 1D by default, whereas NumPy supports multi-dimensional arrays (matrices, tensors).

In [7]:
arr2D = np.array([[1, 2], [3, 4]])
print(arr2D)

[[1 2]
 [3 4]]


## **Vectorization** allows you to perform operations on whole arrays at once, making the code cleaner, faster, and more efficient than using loops.

### 4. Built-in Mathematical Operations
- NumPy provides vectorized operations (addition, multiplication, etc.), making calculations much faster.

In [9]:
lst1 = [1, 2, 3]
lst2 = [4, 5, 6]
# Using List
result_list = [x + y for x, y in zip(lst1, lst2)]

# Using NumPy
arr1 = np.array(lst1)
arr2 = np.array(lst2)
result_numpy = arr1 + arr2  # Faster!

print(result_list)   # [5, 7, 9]
print(result_numpy)  # [5, 7, 9]

[5, 7, 9]
[5 7 9]


### 5. Supports Advanced Functions
- NumPy provides linear algebra, random number generation, and statistical functions, which lists lack.

In [11]:
arr = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(arr))  # 30.0
print("Std Dev:", np.std(arr))  # 14.14

Mean: 30.0
Std Dev: 14.142135623730951


### 6. Easy Data Manipulation (Slicing, Reshaping)
- NumPy provides powerful slicing, reshaping, and filtering capabilities that are complex with lists.

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[:, 1])  # Extract second column → [2, 5]


[2 5]


**4. Installing Numpy Library**

In [15]:
* Install Numpy Package 

  `! pip install Numpy`
* Uninstall Numpy Package 

  `! pip uninstall Numpy`

* Upgrade Numpy Package 

  `! pip install --upgrade Numpy`

* Show Numpy Package 

  `! pip show Numpy`

* Show Numpy Version 

  `np.__version__`

  `  e.g 1.21.5`

  where; 
      1 = Major Number (Big Update)
      21 = Minor Number (Minor Changes)
      5 = Revision Number (Solved Bugs)

* Import Numpy Package 

  `Import Numpy as np`

SyntaxError: invalid syntax (3334831111.py, line 1)

### Check Numpy version


In [8]:
print(np.__version__)

2.2.4


## Creating Arrays
### 0-D Array

In [10]:
ar = np.array(11)
print(ar)

11


### 1-D Array

In [2]:
A = np.array([1,2,3,4])
print("1-D Array :",A)

1-D Array : [1 2 3 4]


### 2-D Array (Matrix)

In [6]:
matrix = np.array([[1,2,3],[3,4,5]])
print(matrix)

[[1 2 3]
 [3 4 5]]


### 3-D Array

In [7]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### `ndim` propery - Check how many dimensions the arrays have

In [12]:
print(ar.ndim)
print(A.ndim)
print(matrix.ndim)
print(arr.ndim)

0
1
2
3


### `shape` propery - It return no of rows and columns (row X column)

In [15]:
print(matrix.shape)

(2, 3)


### `dtype` propery - returns the data type of the array
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [17]:
print(matrix.dtype)

int64


In [18]:
gender = np.array(['Male','Female'])
print(gender)
print(gender.dtype)

['Male' 'Female']
<U6


### `size` propery - returns total no.of elements

In [44]:
print(A.size)
print(matrix.size)

4
6


## Access Array Elements
- Array indexing is the same as accessing an array element.
- You can access an array element by referring to its **index number**.



In [21]:
name = np.array(['Ande','Pavan','Kumar'])
print("index-0 :",name[0])
print("index-1 :",name[1])
print("index-2 :",name[2])

index-0 : Ande
index-1 : Pavan
index-2 : Kumar


### Access 2-D Arrays

In [27]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
# first row first column
print(arr[0,1]) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


### Access 3-D Arrays

In [32]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr.shape) # (depth, rows, columns).
print(arr[1,1,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
11


### Slicing arrays
-  Slicing in python means taking elements from one given index to another given index.
-  **[start:end]** (end means end-1 index)
-  **[start:end:step]**
### 1-D array


In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# Start & End
print(arr[1:5]) 

# Start
print(arr[2:])

#End
print(arr[:4])

#Step by 2
print(arr[0:7:2])

[2 3 4 5]
[3 4 5 6 7]
[1 2 3 4]
[1 3 5 7]


#### Negative Slicing
- Use the minus operator to refer to an index from the end (Negative index starts **-1** from end of array)

In [36]:
print(arr[-3:-1])

[5 6]


### 2-D Array
- **arr[row_start:row_end, col_start:col_end]**

In [54]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr.shape)
print(arr[0:2, 0:3])

(2, 5)
[[1 2 3]
 [6 7 8]]
